language: php

php:
- 7.1
- 7.2

env:
  global:
  - secure: sbGPKj6jiQhY09zMrpsH4Oj20uvp41QjZmNokwfaMVtJUcFRXqlMslnViyr+5Ai08hzUfKVw50SxpHRhVVU7WLZB08wXRLPLRKTsnJgwJ/EjmhC6718Iyg1SmooEOsqOx/q8zivZH6LgCzE1pjWFsA0DuhW5K5EvAdgePaao3H5eajRH6PlkVf+oINibKN9OonOhtZoNZ0BYV38zUohGgzTLK9qql1JvwoUVZxZvZ0MAV+3DtNX3zxY5mI3CU6Eq10IJXUs4yiPMuE3BjRVFBO3uKBQ1e+Sasu8ZdpdEdL9VrmT4PCC1FPXFhsPE8Cp3s6IangZgGejKsmZ1k8B4My0Vt2k1NgstpWu0DhbAf2pG3DDDjOfBk0XZnXqABdm8MXYsXLl7kJKvjEYQxQCiUbyQ55oJkULimAvLM/O43MFuQBMPrerHIM+hsiiXdYNSMl1/Vo775TNAcXnJfwtQ1Uw3eq94XkuKHphOZWQaqcOmTxgp1+mbXat9HucNpFz6SApjkIixTjGdUgtwZmkBCDPpKalg+wGXqi2DriifHgss8EreHUxMVC7FSrWGYPt2l31O9EFe3T0YU60DZACHPY44x7gt0wj4knWBjH/RyB8bcoCCZl7D/mcT8aODQtntd2II+8dsLn1Dw4K24pqsajSt9fb66PrVjvkWZWejDL8=
  - secure: gq3wmTwCP+JYtRFIOH+YDhhdPAr0s+lOajGBRGHV54TOT+jZxV9/ws9Fk6TQNRg0/UBLhMhvXQZWPY+SnUtuh9rP4kqae5A4C/dgLXqsM1nKDMqGYBoy+BlHfwsOrapNM+1QRiDe8VWJrnDvYXg3ocBEHcAqHqBmEsg3YHFedxY5SLi75bbUD4hl9BoMjVF0dXbSCtV6hmLVy/rSYKTJNnOZtVzKTpn2zf+4bzx2gh6MQJRw6EPg992PLWzuidizj54pUKodaQ9xpAPX0ZR6xRbpoMVKyldXk87obB8uYN2MmBp1DD0mHF7lSzKVEVRo0XO5seoF+nteOeLkeJ9ZfEUMwfOClLI1q1sITRZXUUoNzeW95tBkqsBPsuw+MT+Anc7YzHr1Uaok/6v94Y0/HR5kUhGWtfA7p5Ayk0EfqIRy0CA2rOMbG1k7hkzOGu6hP3BvpCvcr80/H7t8XoAcprFmo+csVLlQINqakoU4+d8h28NlXP1xTNs/SbhFSe4iGTmnzmXSkOIwEYHo/TyJFqQan6FNvmDgBQnRjwkmtAghLXS5ypujLyciAAAGgxtLpkS2aIQRUu0/VklDP2CbJhEH/z/GizVkQ1S2W5UtOvBoioNiYr3TTT2RvLQ21IDLoTSRnG7lLMN7hX8pZnD4gqLA+J/Il+XpK93rx6LmhFk=

install:
- echo "{\"http-basic\":{\"nova.laravel.com\":{\"username\":\"${NOVA_USERNAME}\",\"password\":\"${NOVA_PASSWORD}\"}}}" > auth.json

before_script:
- travis_retry composer self-update
- travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
- vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
- php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
